"""add_whatsapp_automation_tables

Revision ID: d9c4b549b632
Revises: 2e226148ea35
Create Date: 2025-11-29 22:02:19.508151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd9c4b549b632'
down_revision: Union[str, None] = '2e226148ea35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('source_groups', sa.JSON(), nullable=True),
    sa.Column('destination_groups', sa.JSON(), nullable=True),
    sa.Column('min_interval_per_group', sa.Integer(), nullable=True),
    sa.Column('min_interval_global', sa.Integer(), nullable=True),
    sa.Column('max_messages_per_day', sa.Integer(), nullable=True),
    sa.Column('plan_name', sa.String(length=50), nullable=True),
    sa.Column('max_source_groups', sa.Integer(), nullable=True),
    sa.Column('max_destination_groups', sa.Integer(), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('messages_sent_today', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('group_name', sa.String(length=200), nullable=False),
    sa.Column('message_id', sa.String(length=200), nullable=False),
    sa.Column('text_hash', sa.String(length=32), nullable=True),
    sa.Column('timestamp', sa.BigInteger(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['whatsapp_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_id', 'group_name', 'message_id', name='uq_message_per_connection')
    )
    op.create_index('idx_conn_group_msg', 'message_logs', ['connection_id', 'group_name', 'message_id'], unique=False)
    op.create_table('offer_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('source_group_name', sa.String(length=200), nullable=True),
    sa.Column('destination_group_name', sa.String(length=200), nullable=True),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('monetized_text', sa.Text(), nullable=True),
    sa.Column('links_found', sa.JSON(), nullable=True),
    sa.Column('preview_generated', sa.String(length=10), nullable=True),
    sa.Column('send_duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['whatsapp_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conn_created', 'offer_logs', ['connection_id', 'created_at'], unique=False)
    op.create_index('idx_dest_group', 'offer_logs', ['destination_group_name'], unique=False)
    op.create_index('idx_source_group', 'offer_logs', ['source_group_name'], unique=False)
    op.create_index(op.f('ix_offer_logs_created_at'), 'offer_logs', ['created_at'], unique=False)
    op.drop_index(op.f('ix_product_history_product'), table_name='product_history')
    op.drop_index(op.f('ix_product_history_product_id'), table_name='product_history')
    op.drop_index(op.f('ix_product_history_scraped_at'), table_name='product_history')
    op.drop_index(op.f('ix_product_history_store_slug'), table_name='product_history')
    op.drop_table('product_history')
    op.drop_index(op.f('idx_whatsapp_instances_status'), table_name='whatsapp_instances')
    op.drop_index(op.f('idx_whatsapp_instances_user'), table_name='whatsapp_instances')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_whatsapp_instances_user'), 'whatsapp_instances', ['user_id'], unique=False)
    op.create_index(op.f('idx_whatsapp_instances_status'), 'whatsapp_instances', ['status'], unique=False)
    op.create_table('product_history',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('store_slug', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('current_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('original_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('discount_percent', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('product_url', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('rating', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True),
    sa.Column('review_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_prime', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('scraped_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('product_history_pkey'))
    )
    op.create_index(op.f('ix_product_history_store_slug'), 'product_history', ['store_slug'], unique=False)
    op.create_index(op.f('ix_product_history_scraped_at'), 'product_history', ['scraped_at'], unique=False)
    op.create_index(op.f('ix_product_history_product_id'), 'product_history', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_history_product'), 'product_history', ['store_slug', 'product_id'], unique=False)
    op.drop_index(op.f('ix_offer_logs_created_at'), table_name='offer_logs')
    op.drop_index('idx_source_group', table_name='offer_logs')
    op.drop_index('idx_dest_group', table_name='offer_logs')
    op.drop_index('idx_conn_created', table_name='offer_logs')
    op.drop_table('offer_logs')
    op.drop_index('idx_conn_group_msg', table_name='message_logs')
    op.drop_table('message_logs')
    op.drop_table('whatsapp_connections')
    # ### end Alembic commands ###
